### ISSUE TITLE
Error when using address argument in eml_party()

### ISSUE THREAD

**Issue by drkrynstrng** [NCEAS/arcticdatautils#117]
For `eml_party()` and its derivatives like `eml_creator()` the address argument does not seem to work. It errors with a character input:

```
> eml_party(type = "contact", organization = "NCEAS", address = "735 State St")
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “character” is not valid for @‘address’ in an object of class “contact”; is(value, "ListOfaddress") is not TRUE
```

The address field in EML is more complicated than the other fields, with subfields including deliveryPoint, city, etc., so this is probably the root of the issue.

**Comment by jeanetteclark** [comment]
No error, just maybe bad documentation. the address element should be a valid EML address field
