### ISSUE TITLE
Update functions that set sysmeta fileName

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/arcticdatautils#126]
Update functions that set the `fileName` field in system metadata to the following conventions:
+ New resource map filenames will be: `resource_map_{UUID-for-RDF}.rdf.xml`
+ Data, metadata, and resource map file names will have all non [A-Za-z0-9] replaced with _ (underscore)

**Comment by jagoldstein** [comment]
reference https://github.com/NCEAS/metacatui/issues/915

**Comment by jagoldstein** [comment]
@dmullen17 please remember to update `update_object` as well

**Comment by dmullen17** [comment]
@jagoldstein yea I added it in the previous commit - just didn't reference it in the commit message. https://github.com/NCEAS/arcticdatautils/pull/130/commits/2999f25982ef3ddba51b665e8d1dd76993177224#diff-cbad68437001c7e024df43fecf5c222bL187
