### ISSUE TITLE
Recover failed submission function

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/arcticdatautils#142]
We should add a `recover_failed_submission` function loosely based on the following script: `'/home/dmullen/R/recover_submission_template.R'`.  Function arguments be `mn`, `pid`, and `path`.  This function should just grab the pid, remove the error message, and write it to the path. 

We could also add optional arguments - like `resource_map_of_package_to_replace` (might need a better name) that does everything in that script including replacing the metadata of the package the PI failed to edit with the recovered metadata.  This might also work better as a separate function that calls `recover_failed_submission`.

**Comment by amoeba** [comment]
Hey @dmullen17, what's a failed submission in this case? I see the lines where you're reading the an object to a char vec and removing `"EML draft.*</error>`"`. What causes that?

**Comment by dmullen17** [comment]
A couple different things can cause it - usually poor internet connection.  @laurenwalker might know better than me.

**Comment by amoeba** [comment]
Ah, gotcha. Thanks.

**Comment by dmullen17** [comment]
Closed by #144
