### ISSUE TITLE
Download script 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/arcticdatautils#145]
@jeanetteclark @amoeba what do you think about adding a helper function that does something similar to this?  This is just a script I modify from time to time so it's not very clean.

```
pkg <- get_package(adc, 'resource_map_doi:10.5065/D61J97TT', file_names = T)
pid_to_wget <- function(pid) {
  return(paste0('wget https://arcticdata.io/metacat/d1/mn/v2/object/', pid, ' -O ', names(pid), '\n'))
}

pids <- c(pkg$metadata, pkg$data)
text <- vector('character', length(pids))
for (i in seq_along(pids)) {
  text[i] <- pid_to_wget(pids[i])
}
formatted_text <- paste0(text, collapse = '')
write(formatted_text, file = '/home/dmullen/Submissions/Merrelli/download.sh')
```

**Comment by amoeba** [comment]
I saw the RT ticket that probably prompted this. I think it's a good script to have somewhere since it comes up every once in a while. It's a little more general than arcticdatautils though, could datamgmt be place for it? I'm not overly picky here.

As for what the script does, it looks good.

**Comment by dmullen17** [comment]
Yea `datamgmt` seems like a better place for it.  

As kind of an aside each call to `wget` throws an authentication error that doesn't end up interfering but is annoying.  So i decided to add the `--no-check-certificate` argument.  It's increased the download time by orders of magnitude.  With `--no-check-certificate` it took `real	0m29.750s`.  I'm still waiting on the time to return for the other case but it's been over 30 minutes.

**Comment by amoeba** [comment]
Hrm, weird. Let me give it a go here and see. Maybe we have a config issue.

**Comment by amoeba** [comment]
Which version of wget are you using? I don't get any errors or warnings. I'm on GNU Wget 1.20.3.

**Comment by dmullen17** [comment]
Just updated to Wget 1.20.3.  Upon further inspection the file sizes are all 0 bytes if you don't include `--no-check-certificate` 🤦‍♂

**Comment by amoeba** [comment]
Weird, no issues here. My script has lines like:

```

**Comment by dmullen17** [comment]
Yea it also worked the PI that I sent the script to.  I think we should include --no-check-certificate` just to be safe.
