### ISSUE TITLE
encode physical section URLs

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/arcticdatautils#161]
`pid_to_eml_physical` automatically generates download URLs from the pid. These should be URL encoded, which is congruent with what metacatUI does (see https://github.com/NCEAS/metacatui/issues/523).

**Comment by amoeba** [comment]
@jeanetteclark asked me to take a quick scan and I found three spots to update:

https://github.com/NCEAS/arcticdatautils/blob/master/R/eml.R#L106:L106
https://github.com/NCEAS/arcticdatautils/blob/master/R/eml.R#L1150:L1150
https://github.com/NCEAS/arcticdatautils/blob/master/R/eml.R#L106:L106

I looked for:

- Calls to `EML::set_physical`
- Strings with "cn/v2", "resolve", and "object"

**Comment by laijasmine** [comment]
assigning this issue to myself in comments because I don't have the permission to
