### ISSUE TITLE
develop semantic annotation helper functions

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/arcticdatautils#172]
To make supporting EML2.2.0 easier we should consider developing some helper functions

- [ ] get a list of classes from https://bioportal.bioontology.org/ontologies/OBOE/?p=classes to choose from
- [ ] a function that gets the `propertyURI` when given a label?
- [ ] a similar function that gets the `valueURI`

**Comment by laijasmine** [comment]
potentially to tweak this for our uses:
https://www.bioontology.org/wiki/Annotator_R_Client

**Comment by amoeba** [comment]
Heya @laijasmine, let me know if you have any questions about EML annotations, semantic search, OBOE/ECSO, BioPortal, etc. I'm excited to see what the team comes up with here.

One note: BioPortal has a handy Term Search API endpoint (documented at http://data.bioontology.org/documentation#nav_search) which can be used to find the most likely term(s) given a free text input (i.e., an `attributeName`). They have other API endpoints that may be of use too.

**Comment by laijasmine** [comment]
Thanks @amoeba ! I can see that I will have lots of questions as I dig deeper into this.

**Comment by mbjones** [comment]
Also, I think the best place for new helper functions for semantic annotations is in the `EML` package and not in `arcticdatautils`. The only thing that should go in `arcticdatautils` are functions that only are useful to the Arctic Data Center. Anything that has general utility should go elsewhere.

**Comment by jeanetteclark** [comment]
Good catch - yes this should definitely go in EML

**Comment by laijasmine** [comment]
ah ok will move this over there thanks!
