### ISSUE TITLE
Rename the master branch to main

### ISSUE THREAD

**Issue by csjx** [NCEAS/arcticdatautils#186]
From an inclusivity perspective, I suggest we rename the `master` branch to `main` and generally use more welcoming terms as we describe our software architectures. The use of the the terms `master` and `slave` in computing are not welcoming.  For context, see the [Inclusive Naming](https://inclusivenaming.org) project and [this repo](https://github.com/github/renaming).

**Comment by laijasmine** [comment]
yes! been wanting to do this! Will make a point to do this by the end of the week before it slips off my to-do list again!

**Comment by laijasmine** [comment]
Done!
