### ISSUE TITLE
Improve token set/expiry methods to handle multiple tokens

### ISSUE THREAD

**Issue by amoeba** [NCEAS/arcticdatautils#2]
If two tokens are set, weird stuff happens.

**Comment by gothub** [comment]
@amoeba Is this a problem with the dataone R client token handling?

**Comment by amoeba** [comment]
Not actually sure yet. It crops up when a user has set both a production and a test token. I'll see if I can figure it out real quick.

**Comment by amoeba** [comment]
At the very least, this is kind of weird behavior:

```{R}
> dataone::getTokenInfo(dataone::AuthenticationManager())
No tokens are currently defined.
> options(dataone_token="X")
> dataone::getTokenInfo(dataone::AuthenticationManager())
Error in unlist(strsplit(authToken, "\\."))[[2]] : 
  subscript out of bounds
> options(dataone_test_token="Y")
> dataone::getTokenInfo(dataone::AuthenticationManager())
Error in unlist(strsplit(authToken, "\\."))[[2]] : 
  subscript out of bounds
```

**Comment by amoeba** [comment]
Oh, that's just because I set bogus tokens. Let me set real ones and test.

**Comment by amoeba** [comment]
Yeah, this looks good on the rdataone end. Just a bug on my end.
