### ISSUE TITLE
Remove EML access sub-trees when updating EML metadata

### ISSUE THREAD

**Issue by amoeba** [NCEAS/arcticdatautils#4]
Metadata documents created or edited by the registry script end up with EML `access` elements at the `/eml/dataset` level which are no longer respected by Metacat. The R package currently leaves these in tact when updating packages but it would be better if it removed them.

In the `publish_update` function, when updating the `packageId` and `system`, also remove any EML `access` elements before calling `updateObject()`.

**Comment by amoeba** [comment]
This can still be done. If someone picks this up, I'd like to see a unit test or two to go with it (I can help with this part).

**Comment by dmullen17** [comment]
@amoeba I'll pick this up.  It looks like it's just a matter of setting eml@access <- new("access") in the right places?  

And I think I can make unit tests based on the ones you've written

**Comment by amoeba** [comment]
Thanks @dmullen17, I think that'll work. Ideally we'd only nuke the access section if the function the user ran was already going to end up in an updated EML Object (i.e., `publish_update` doesn't always update the EML Object with a new one).
