### ISSUE TITLE
Add userID argument to eml_party functions

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/arcticdatautils#40]
Need to add a userID argument to eml_party functions to easily incorporate adding ORCIDs to EML in datateam workflow

`eml_creator`
`eml_contact`
`eml_associated_party`

**Comment by amoeba** [comment]
This is great, thanks for filing. Do you or an data team member wanna take a crack at this?

**Comment by jeanetteclark** [comment]
yeah I can do it, not happening before I go out of town though. If someone gets to it before me then great!

**Comment by jeanetteclark** [comment]
done (I think) and added a pull request (#41)

**Comment by amoeba** [comment]
Thanks! I merged the PR and added a commit with some minor tweaks on top: https://github.com/NCEAS/arcticdatautils/commit/8c242e8ae3ce102648368e82218d1902faa3b79c
