### ISSUE TITLE
Setting Up Authentication in Unit Tests

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/arcticdatautils#43]
### Issue
While running the articdatautils, three tests are skipped, and fifteen failures are detected. I believe this issue has to do with my session token. I set a browser() breakpoint, which can be seen in the dump below, but can be ignored.

It appears that the issue isn't with code integrity, rather it is a problem with my session token. I believe this is the case because before the failures, tests were skipped due to one not being set. The failures are also occurring in code that depends on the token.

Every error also fails at the same point, and follows the same trace. 

This can be marked as very low priority, I'm not using arcticdatautils-only playing with the code base.

### Dump
> options(dataone_test_token = "...")
> devtools::test()
Loading arcticdatautils
Testing arcticdatautils
access: 1234Called from: eval(code, test_env)
Browse[1]> c
5
dataone: SSS
formats: ..
editing: 6789ab.cdef..
EML: ............................E
environment: ......
helpers: E
inventory: .......................
packaging: ....
sysmeta: .....
util: ...........

Skipped ---------------------------------------------------------------------------------------------------------------------------------------
1. permissions can be checked (@test_dataone.R#7) - No token set. Skipping test.

2. permissions can be checked on multiple objects (@test_dataone.R#16) - No token set. Skipping test.

3. checking permissions on a missing object returns an error (@test_dataone.R#27) - No token set. Skipping test.

Failed ----------------------------------------------------------------------------------------------------------------------------------------
1. **Error**: get_package works for a simple package (@test_access.R#10) --------------------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_access.R:10
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

2. **Error**: get_package works for a package with a child package (@test_access.R#24) ------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_access.R:24
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

3. **Error**: get_package works for an object in two packages (@test_access.R#48) -----------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_access.R:48
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

4. **Error**: get_package works the same when given a metadata pid as it does when given a resource map pid (@test_access.R#62) -------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_access.R:62
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

5. **Error**: get_package returns a warning if the package doesn't exist (@test_access.R#74) ------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mnn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_access.R:74
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

6. **Error**: we can publish an update (@test_editing.R#11) ---------------------------------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:11
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

7. **Error**: an identifier can be manually specified when publishing an update (@test_editing.R#30) ----------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:30
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

8. **Error**: we can create a resource map (@test_editing.R#50) -----------------------------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_metadata(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:50
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:14
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

9. **Error**: we can update a resource map (@test_editing.R#66) -----------------------------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:66
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

10. **Error**: an object can be published with a SID (@test_editing.R#97) -------------------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: publish_object(mn, tmp, "text/csv", sid = new_sid) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:97
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/editing.R:55
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

11. **Error**: SIDs are maintained when publishing an update to an object with a SID (@test_editing.R#118) ----------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: publish_object(mn, metadata_path, "eml://ecoinformatics.org/eml-2.1.1", sid = new_sid) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:118
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/editing.R:55
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

12. **Error**: we can publish an update to an object (@test_editing.R#139) ------------------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_object(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:139
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:58
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

13. **Error**: we can publish an update to an object and specify our own format id (@test_editing.R#160) ------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_object(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:160
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:58
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

14. **Error**: extra statements are maintained between updates (@test_editing.R#179) --------------------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn, 3) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:179
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

15. **Error**: rightsholder is properly set back after publishing an update (@test_editing.R#218) -------------------------------------------------
parse error: premature EOF
                                       
                     (right here) ------^
1: create_dummy_package(mn) at C:\Users\Data\Documents\GitHub\arcticdatautils/tests/testthat/test_editing.R:218
2: get_token_subject() at C:\Users\Data\Documents\GitHub\arcticdatautils/R/helpers.R:98
3: dataone::getTokenInfo(dataone::AuthenticationManager()) at C:\Users\Data\Documents\GitHub\arcticdatautils/R/util.R:607
4: dataone::getTokenInfo(dataone::AuthenticationManager())
5: getTokenDetails("dataone_test_token")
6: parseAuthToken(authToken)
7: fromJSON(payloadChar)
8: fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, 
       ...)
9: parseJSON(txt, bigint_as_char)
10: parse_string(txt, bigint_as_char)

DONE ==========================================================================================================================================

### Session Info
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dataone_2.1.0         arcticdatautils_0.6.1 datapack_1.3.1        EML_1.0.3             XML_3.98-1.9          testthat_1.0.2       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     compiler_3.4.1   plyr_1.8.4       bindr_0.1        base64enc_0.1-3  tools_3.4.1      ncdf4_1.16       digest_0.6.12   
 [9] uuid_0.1-2       jsonlite_1.5     memoise_1.1.0    tibble_1.3.4     pkgconfig_2.0.1  rlang_0.1.2      rstudioapi_0.7   commonmark_1.4  
[17] curl_2.8.1       yaml_2.1.14      bindrcpp_0.2     withr_2.0.0      httr_1.3.1       stringr_1.2.0    dplyr_0.7.3      roxygen2_6.0.1  
[25] xml2_1.1.1       devtools_1.13.3  redland_1.0.17-9 glue_1.1.1       parsedate_1.1.3  R6_2.2.2         hash_2.2.6       magrittr_1.5    
[33] assertthat_0.2.0 stringi_1.1.5    crayon_1.3.4

**Comment by amoeba** [comment]
Thanks for the highly-detailed Issue! I think the issue lies in how you're setting your authentication token. The test suite can run integration tests (conditional on a authentication token being set) which interact with a testing DataONE Member Node and these tests require an authentication token. The snippet of code in the README:

```r
# Set a token to run skipped tests:
options(dataone_test_token = "...")
devtools::test()
```

is vague on that fact that it's an example snippet and needs modification before being run. The intention is for you to get a testing authentication token from https://test.arcticdata.io but *how* anyone other than someone intimately familiar with our services would know that is beyond me. Apologies for the lack of instruction.

Am I correct in that you just ran that as-is and didn't replace the `options` call with code thats sets an authentication token? With a valid token, the test suite runs without error for me.

**Comment by amoeba** [comment]
BTW: I've updated the readme a bit to be more clear about this: https://github.com/NCEAS/arcticdatautils#testing

**Comment by ThomasThelen** [comment]
Thanks that fixed it all!
