### ISSUE TITLE
update dataone formatIDs

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/arcticdatautils#44]
the list of formatIDs called by the package needs to be updated. I couldn't find the actual list but did find where it is referenced:

from `publish_object`

``` # Check if format ID is valid
  if (!(format_id %in% D1_FORMATS)) {
    stop(call. = FALSE,
         paste0("The format_id of '", format_id, "' is not a valid format ID. See https://cn.dataone.org/cn/v2/formats for the current list. This package stores a copy and may be out of date with that list so please email the author if needed."))
  }```

**Comment by amoeba** [comment]
The variable D1_FORMATS is stored in R/sysdata.rda which is an R package development convention so it's hard to find without magically knowing that.

To fix the ultimate issue which is the potential for a discrepancy between this cached set of format IDs and the actual set of format IDs on the CN, I guess we could do two things:

1. Update this file and re-release the package
  - Pros: Fixes the problem for now
  - Cons: Does not prevent the problem from cropping up again
2. We could make the package load a fresh list every time it's loaded (e.g. via `library`)
  - Pros: Fixes the problem now and in the future, so long as the user doesn't keep long-running R sessions going. e.g., if a person loads the package, then the CN's list changes, the person's list will still be out of sync
  - Cons: Increases package startup time by about 2 seconds

Thoughts? I feel okay with (2)

**Comment by jeanetteclark** [comment]
I feel okay with (2) as well. 2 seconds seems like something we can handle.

Thanks Bryce!

**Comment by amoeba** [comment]
I'm glad it's Friday. After I added this feature, I re-ran Sharis' code and realized this wasn't actually her problem. She had a typo in her format ID:

Hers: `application/vnd.google-earth.kml/xml` (wrong)
DataONE's: `application/vnd.google-earth.kml+xml` (right)

But anyway, this feature is done.

**Comment by jeanetteclark** [comment]
Oh dear. Yes. Thankfully it's Friday. I guess this is what happens when bugs come in while Jesse and I are out at lunch 😳 Sorry about the false alarm
