### ISSUE TITLE
eml_metadata_provider(): “metadata_provider” is not a defined class

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/arcticdatautils#46]
Function `eml_metadata_provider` needs updating.

```Error in getClass(Class, where = topenv(parent.frame())) :```
```“metadata_provider” is not a defined class```

**Comment by amoeba** [comment]
Thanks for the report! @jeanetteclark already PR'd this and I've merged it: https://github.com/NCEAS/arcticdatautils/pull/45. Please re-open this Issue if it crops up again.
