### ISSUE TITLE
Modify rights/access functions to prevent use of `https` ORCID URIs

### ISSUE THREAD

**Issue by amoeba** [NCEAS/arcticdatautils#47]
Functions like `set_rights_and_access` can be passed any `Subject` and a common mistake is to pass in an HTTPS ORCID URI for a `Subject`. This is a problem because DataONE only uses the HTTP form and doesn't consider the HTTPS variant to be equivalent. So, currently, the user has to be careful to not to use the HTTPS form.

The various functions that set `rightsHolder` and `accessPolicy` information on SysMeta could easily check for this specific case.

**Comment by mbjones** [comment]
I think we should reconsider whether this is the right decision.  ORCID itself recommends the https form.  We recommended that LTER use the https form.  And I have been recommending that other groups use the https form.  I'm not sure how DataONE ended up using the http form, but I'll bet it was accidental and not a specific design decision.  If we change anything, it should probably be changing DataONE to use https, and update the existing access rules to their https form (which I think would be very safe in this specific ORCID case).

**Comment by amoeba** [comment]
Certainly an important issue. We have a related thread going on at https://redmine.dataone.org/issues/8215 which hasn't moved far but can be kickstarted. Probably the best place to discuss this though since, for now, we only support HTTP URIs for ORCID Subjects.

**Comment by jeanetteclark** [comment]
closing this, I fixed this issue a while back to automatically convert https to http, which fixes the arcticdatautils side of things.

Matt's issue above is still outstanding, but needs to be handled in dataone land
