### ISSUE TITLE
Fix inconsistent use of checksumAlgorithm

### ISSUE THREAD

**Issue by amoeba** [NCEAS/arcticdatautils#52]
When creating new System Metadata records, this package is sometimes using a `checksumAlgorithm` of SHA1 and sometimes SHA-1. This is technically valid but, in reality, probably a bad thing. Also see https://github.nceas.ucsb.edu/KNB/arctic-data/issues/283 as it relates to the issue there.

1. Find the right way to write algorithm names
2. Change the relevant sections of code to reflect that change

**Comment by jeanetteclark** [comment]
this was fixed in PR #175
