### ISSUE TITLE
update_object doesn't update identifier field for EMLs

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/arcticdatautils#53]
Using `update_object` to update a metadata record doesn't set the packageId (eml@packageId) as the pid of the most recent version.  
I'd be happy to update this (if it's a worthy change) - filing it as an issue so I don't forget.

**Comment by amoeba** [comment]
Good catch! I think `update_object` should be changed to do what you describe. Hanging on to old `packageId` values is definitely bad for our workflow here.
