### ISSUE TITLE
Figure out R 3.5 Travis issues

### ISSUE THREAD

**Issue by isteves** [NCEAS/arcticdatautils#86]
Travis is unhappy with the add-ons specified in the yml (especially [ncdf4](https://packages.debian.org/buster/r-cran-ncdf4)) when tested in the devel/release R environment.  (It's happy in the old release.) 

So far I've tried:

- removing `cache: packages` - suggested in various places, including [here](https://github.com/r-spatial/sf/issues/729)
- adding `update: true`

In datateam-training, I only test Travis on the old release now, which fixes the problem temporarily.

[This post](https://stat.ethz.ch/pipermail/r-sig-debian/2018-April/002829.html) also seems pretty useful, but I don't fully understand it.

Writing an issue here bc I'll have to come back to this later.

**Comment by amoeba** [comment]
Odd. The error I see on the failed build relates to a GPG key for MongoDB. [This](https://github.com/travis-ci/travis-ci/issues/8554) makes it look like a more general Travis CI issue and not with our repo. Looks kinda like having to install ncdf4 is causing the Travis issue to crop up.

This is an easy fix: arcticdatautils shouldn't need ncdf4 anyway. It should've been a `Suggests` all along so I'm going to fix that now. I'll also look at the other dependencies to see if they some can be removed or moved to `Suggests`.

**Comment by isteves** [comment]
Hopefully that works!  Haven't checked to see if the other addons also break.

**Comment by amoeba** [comment]
Yeah it might not be the fix: We still require `librdf0-dev` which means we need to run `apt-get`.

**Comment by amoeba** [comment]
Appears to be [happy](https://travis-ci.org/NCEAS/arcticdatautils/jobs/377495813) now. Triggered one more build to clean up the `Depends` list but I think this is good. I"m heading out but will check back later. Please feel free to close if the current build comes back ♦️ .

**Comment by isteves** [comment]
Thanks @amoeba and @cboettig for figuring this out!
