### ISSUE TITLE
create_dummy_x functions shouldn't work on PROD

### ISSUE THREAD

**Issue by maier-m** [NCEAS/arcticdatautils#93]
Create functional tests to prevent functions of the type `create_dummy_x` to fail if tried on a PROD node.
These types of functions should only be used on non-Production nodes.

Also, make sure all unit tests use `create_dummy_x` functions when applicable so that they are guaranteed to not publish on PROD.

**Comment by dmullen17** [comment]
@jagoldstein what do you think about this one?  I'm leaning towards closing it without making this change because these functions can be used for testing on production nodes.

**Comment by jagoldstein** [comment]
@dmullen17 you have used this function on PROD proving that there are use cases where this function is helpful on PROD.

I am ok with closing it but perhaps @amoeba has a different opinion.

**Comment by jagoldstein** [comment]
oops, did not mean to close it yet

**Comment by jeanetteclark** [comment]
right now the function will not let you publish on `prod` and it seems like we haven't come up with a use case yet, so if it is used it is infrequent. I vote we keep Mitchell's change and close. Feel free to reopen if anyone thinks otherwise
